### ISSUE TITLE
JavaScript ERROR

### ISSUE THREAD

**Issue by Sark934** [4dams/LeagueToolkit#10] opened 2018-02-26 20:47 UTC
![fsdghj](https://user-images.githubusercontent.com/36864401/36694400-99a1348e-1b3e-11e8-84c0-e9858fcdd0a9.png)

Client is running and up-to-date, all files have been extracted.

**Comment by Xh4H** [comment] 2018-02-27 08:03
Was your League Client open?

**Comment by Sark934** [comment] 2018-02-27 08:41
Yes

**Comment by juriadams** [comment] 2018-03-07 19:52
Hey, sorry for the long response time... Will now look into the issue :)

**Comment by juriadams** [comment] 2018-03-09 14:02
Hmm... That's really weird... We have tried reproducing this bug now but couldn't manage to do so.

Here are some things you may wanna check before launching the app:
- You have downloaded the latest release and extracted **all** files from the .zip into a new (empty) folder on your Desktop (or anywhere else)
- The League of Legends client is running and you are logged in

It would be really appreciated if you could reply again to this issue when you've completed these steps, even if it still doesn't work.

**Comment by Sark934** [comment] 2018-03-11 12:26
Hello thanks for trying to solve my problem.
I downloaded the new version (LeagueToolkit-0.2.zip) and I logged into my account but the bug is still here.
I have reinstall the game but without success too. 
![qsfqdghjhj](https://user-images.githubusercontent.com/36864401/37253229-1ad53682-252f-11e8-913e-9c7d6ea8a063.png)

**Comment by juriadams** [comment] 2018-03-12 19:13
This is indeed really weird...
We're also unable to reproduce this so it's gonna be harder to fix this... My guess is that the app is unable to connect with the client/find the client.

Have you tried running the app with administrator privileges? Or have you changed anything with the client installation?

**Comment by Sark934** [comment] 2018-03-14 08:38
"Have you tried running the app with administrator privileges?"  Yes all the time.
"Or have you changed anything with the client installation?" Maybe my game is not in the good folder and the app can't find him ? So i need to install the game in the base folder ?
I have C: and D: disk maybe a problem with this ?

**Comment by Sark934** [comment] 2018-03-14 11:54
Okay I have instal my league client on my SSD (disk C:) and the app is working !

**Comment by juriadams** [comment] 2018-03-14 17:24
That's nice to hear! I hope it's fully functional now, as it is intended to! 
I will try to find a fix for this and you helped a lot tracing this bug down, thanks!

If there are any other issues, let me know! And have fun with the app!

**Closed as completed** 2018-03-14 17:25 UTC
Labels: bug

**Comment by Manerr** [comment] 2018-04-29 14:15
Same error
https://i.imgur.com/llUOo0Y.jpg
